//
//  Find the Difference.cpp
//  LeetCode by zhaowei
//
//  Created by Zhao Wei on 9/23/16.
//  Copyright © 2016 Zhao Wei. All rights reserved.
//

///@file    Find the Difference
///@author  Wei Zhao
///@date    2016.09.23
///@version 1.0

/*
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 */

#include <string>

using namespace std;

class Solution {
public:
    ///@brief   find the added char in t
    ///@param   s   the original string
    ///@param   t   the shuffle string from s and plus an additional char
    ///@return  the addition char in t
    ///@note    1. count the char appearance in t
    //          2. enumerate all the characters in s, and minus the count in t
    //          3. the last one left is the additional character
    char findTheDifference(string s, string t) {
        int cnt[26] = {0};
        for (int i = 0; i < t.length(); i++)    cnt[t[i] - 'a']++;
        for (int i = 0; i < s.length(); i++)    cnt[s[i] - 'a']--;
        for (int i = 0; i < 26; i++)
            if (cnt[i])
                return char('a' + i);
        return ' ';
    }
};

int main() {
    string s = "abc", t = "aecb";
    Solution slt;
    char ch = slt.findTheDifference(s, t);
    return 0;
}






































